Edit card
capener-cade/kanban-express pull request #4
Opened 2021-03-25 08:44 UTC by capener-cade

Added another put endpoint for updating a description and title of a card.

2021-03-25 14:57 UTC, ifit-colin requested changes

2021-03-25 14:57 UTC, ifit-colin commented on src/index.ts
> +app.put("/api/card/:boardId/:cardId", async (req, res) => {
This function will never get hit because it has the same endpoint as the one above.  These should be consolidated into a single function.

2021-03-25 14:57 UTC, ifit-colin commented on src/index.ts
> +    await Card.findByIdAndUpdate(req.params.cardId, { column: req.body.column });
This doesn't do any of the validation that happens on `save`.  We can review this more together.

2021-04-01 03:14 UTC, capener-cade commented on src/index.ts
> +app.put("/api/card/:boardId/:cardId", async (req, res) => {
I combined them into a single function, and made it so all properties are being sent on each request so we don't get any null values.

2021-05-11 15:21 UTC, merged